import Head from "next/head";
import Link from "next/link";
import Layout from "@components/Layout";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <div className="container">
          <h1>Hello</h1>
          <Link href="/products">All Products</Link>
        </div>
      </Layout>
    </>
  );
}
